name: CI

on:
  push:
    branches: 
      - master
    tags:
      "*-release"
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Install and run Luacheck
        uses: nebularg/actions-luacheck@v1
        with:
          args: "--no-color -q"
          annotate: warning
      
      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!
